name: Dummy Test Only

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest and selenium
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium

      - name: Run only the dummy test file
        run: pytest -vv tests/test_dummy.py
