name: Dummy Test Only

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show repo files
        run: |
          pwd
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest only
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run only the dummy test
        run: pytest -vv -k test_dummy
